apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app : angular  
    spec:
      containers:
        - name: angular
          image: mpozega/angular
          imagePullPolicy: Always
          ports:
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: angular 
  name: angular
spec:
  type: ClusterIP
  ports:
  - name: angular
    port: 8001
    protocol: TCP
  selector:
    app: angular
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: angular 
  name: angular-lb
spec:
  type: LoadBalancer
  ports:
  - name: angular
    port: 8001
    protocol: TCP
  selector:
    app: angular